class ParkingSlot:
    def __init__(self, data):
        self.ParkingID = data["ParkingID"]
        self.NextWall = data["Wall"]
        self.NearExit = data["Exit"]
        self.Sunlight = data["Sunlight"]
        self.Column = data["Column"]
        self.Charging = data["Charging"]
        self.Disabled = data["Disabled"]
        self.PathID = data["PathID"]
        self.LocID = data["LocID"]
        self.Fire = data["Fire"]
        self.Bump = data["Bump"]
        self.Temp = data["Temp"]
        self.Lift = data["Lift"]
        self.Stair = data["Stair"]
        self.Corner = data["Corner"]
        self.Mirror = data["Mirror"]
        self.Minisight = data["Minisight"]
        self.camera = data["camera"]
        self.Limit = data["Limit"]
        self.Occupied = data["Occupied"]
        self.Around = data["Around"]

